"""creacion de nuevo campo en la tabla usuarios para la comprobacion de edad

Revision ID: 1b637cdc522f
Revises: 0fc9a0cc6349
Create Date: 2026-03-23 19:51:48.117250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b637cdc522f'
down_revision: Union[str, Sequence[str], None] = '0fc9a0cc6349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isAdult', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isAdult')
    # ### end Alembic commands ###
