"""crear tablas iniciales

Revision ID: 7f2a5c79866f
Revises: 
Create Date: 2026-03-17 13:11:47.235084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f2a5c79866f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('anime', 'manga', name='mediatype'), nullable=False),
    sa.Column('id_api', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_api', 'media_type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'user', name='rol'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('email')
    )
    op.create_table('friendship',
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('friends', 'pending', name='friendshipstatus'), nullable=False),
    sa.Column('datefrienship', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('requester_id', 'receiver_id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True,nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_api', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('anime', 'manga', name='mediatype'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_user')
    )
    op.create_table('userfavorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('watching', 'completed', 'pending', name='status_favorite'), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'favorite_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userfavorite')
    op.drop_table('review')
    op.drop_table('friendship')
    op.drop_table('users')
    op.drop_table('favorite')
    # ### end Alembic commands ###
